encryptionsalt: v1:AVftSJi9yMM=:v1:3MzoIHm1KYSMyCF+:fNRxtMwvYLS+0qIa9DpJh/JURUM7UA==
config:
  kubeContext: kind-lab
  namespace: lab
  deploymentName: lab-deploy
  image: ghcr.io/christiancostap/platform-challenge
  tag: 8f9344c5ce25
  replicas: 2
  serviceName: lab-svc
  servicePort: 8081
  targetPort: 8081